### ISSUE TITLE
Barriers arent visible on 1.20.1 [2.0.4]

### ISSUE THREAD

**Issue by Boy0000** [AmyMialeeMods/visiblebarriers#27]
None of the barriers in front of me shows up

![image](https://github.com/AmyMialeeMods/visible-barriers/assets/62521371/405f8f6a-a8dd-4560-9183-ac100cfffbb7)

**Comment by Boy0000** [comment]
still having this issue on latest release... any clue? conflicting mods or something?

![image](https://github.com/AmyMialeeMods/visiblebarriers/assets/62521371/5e1a922e-e347-42a2-b224-4acbd8832352)

**Comment by AmyMialee** [comment]
what mods are there? or resource packs

**Comment by Boy0000** [comment]
no RP is on really

https://github.com/AmyMialeeMods/visiblebarriers/assets/62521371/69bb22a6-ac35-4a2f-bd78-ed2eb08f44c0

**Comment by Boy0000** [comment]
Tried disabling everything but same problem...
Video shows me on a brand new instance i made, adding fabricapiu and VB and it works
Also shows me on my old instance, with only enabled mods being fabricapi and VB, and it does not work

https://github.com/AmyMialeeMods/visiblebarriers/assets/62521371/79d1db29-1f90-4810-8477-5a8a513e7cf3

**Comment by LysiBee** [comment]
> no RP is on really
> 
>  Desktop.2023.12.06.-.16.15.48.03.mp4

Have you tried to disable Nvidium?
