### ISSUE TITLE
Make it possible to see the marker entity

### ISSUE THREAD

**Issue by Go0g1eZ** [AmyMialeeMods/visiblebarriers#33]
How hard is it to implement, and it is possible to make it so that the "CustomName" is still visible

**Comment by AmyMialee** [comment]
You can already see them but only if the mod is installed on the server too, and you have visibility enabled.
I'm not sure if it shows customname though, if not then I'll add it in the overhaul.

**Comment by AmyMialee** [comment]
assuming working as intended
