### ISSUE TITLE
Pick Block issue with ViaFabricPlus/ViaFabric

### ISSUE THREAD

**Issue by fantomitechno** [AmyMialeeMods/visiblebarriers#35]
When using 
- Visible Barriers 2.0.8
- ViaFabricPlus 2.8.5

the block picking feature always picks air blocks even when looking at solid blocks, ultimately it leads to loosing entirely the block picking

**Comment by AmyMialee** [comment]
hm feels like the litematica issue.

I'll be trying eliminate this issue in the overhaul. At worst I'll just make air itself not pickable cause like nobody uses it lol.

**Comment by AmyMialee** [comment]
gonna close this just because it is planned in that rewrite, if it exists after that then feel free to reopen and yell at me about it lol
