### ISSUE TITLE
Adjustable Zoom System

### ISSUE THREAD

**Issue by AmyMialee** [AmyMialeeMods/visiblebarriers#36]
Slider from about 50% to 100000% (current max, current min is 100%)
Sliders for min, max and lock.
Min and max are always 1 unit apart at least, with max greater than min.
Lock is a value that can go anywhere and you can activate with a different keybind that will lock zoom to that value until pressed again. (also button in the ui to toggle it).
Hitting lock while already zooming will lock at that value instead.
Zoom transition options, smoothed or instant.

**Comment by AmyMialee** [comment]
could make it it's own mod? it is very handy for mapmaking but i feel it could do fine as it's own mod
might work on it when i do my new mod setup and have them share their setup

**Comment by YoshiRulz** [comment]
Something like [Zoomify](https://modrinth.com/mod/zoomify)?

**Comment by AmyMialee** [comment]
honestly yeah that looks like it'll do all or most of what I wanted to do
