### ISSUE TITLE
Minecraft crashes when breaking waterlogged light

### ISSUE THREAD

**Issue by Dudunkin** [AmyMialeeMods/visiblebarriers#37]
Minecraft crashes when I'm trying to break a waterlogged light block (when it is visible via the mod), and sometimes when other waterlogged blocks. It's definetly a problem with visible barriers mod, because other people reported it aswell.

Logs:
[crash-2023-08-30_18.46.50-client.txt](https://github.com/AmyMialeeMods/visiblebarriers/files/12477741/crash-2023-08-30_18.46.50-client.txt)

**Comment by Dudunkin** [comment]
Crash happens if I break any waterlogged block when all visibility is enabled.

**Comment by omoflop** [comment]
I think this crash was inadvertently fixed in PR https://github.com/AmyMialeeMods/visiblebarriers/pull/40
If you go ahead and test it, let me know if it still occurs and I'll try my best to patch it

**Comment by AmyMialee** [comment]
assuming as fixed, reopen if wrong
