### ISSUE TITLE
[Suggestion] Add face culling to barriers, light blocks etc.

### ISSUE THREAD

**Issue by HappyAlexRomania** [AmyMialeeMods/visiblebarriers#50]
When I use lots of lightblocks/barriers in my maps, the game is lagging because of the faces that are being rendered for the visible blocks. I suggest adding face culling for them for performance (for example, face culling like leaves/glass blocks)

**Comment by AmyMialee** [comment]
originally the idea was that it would be beneficial to be able to tell how deep it is but yeah I think it would be nicer to just cull, especially for some rooms that are totally full of light blocks.
