### ISSUE TITLE
bug? i can see other blocks that arent blocks? 

### ISSUE THREAD

**Issue by NobleSkye** [AmyMialeeMods/visiblebarriers#58]
![image](https://github.com/AmyMialeeMods/visiblebarriers/assets/118846397/702946ef-f26d-4a7e-8e1c-de9772044487)
not light blocks not barriers not any block ive seen, looks like pistons but not sure

**Comment by AmyMialee** [comment]
Yea this is another block used in mapmaking, the mod shows all of these kinds of blocks.
