### ISSUE TITLE
Unsupported on Quilt

### ISSUE THREAD

**Issue by BouncyBonBon** [AmyMialeeMods/visiblebarriers#59]
Curseforge lists the mod as compatible with the Quilt launcher, however due to Fabric being a dependency Quilt doesn't let you play with the mod installed. 

Please add support to Quilt or fix this bug! (idk if its a compatibility issue or just a bug)
![image](https://github.com/AmyMialeeMods/visiblebarriers/assets/98642405/dfe493ba-b0fc-48de-93d3-e44047d69978)

**Comment by AmyMialee** [comment]
you need quilted fabric api on quilt
