### ISSUE TITLE
[bug] does not work on mac

### ISSUE THREAD

**Issue by Thinkseal** [AmyMialeeMods/visiblebarriers#63]
all blocks that are meant to be made visible are not made visible on mac I tested this in a modpack with a lot of mods and a modpack that just had this mod a fabric api

**Comment by AmyMialee** [comment]
I'm not sure that I'll be able to do anything about this given I don't have a mac.

**Comment by Thinkseal** [comment]
I was being stupid and I figured out the problem and I understand why I did not think it was working and that is a completely separate bug and a design issue, but they are not not working
