### ISSUE TITLE
[bug] when visible barriers are disabled, the barrier particles don't show up

### ISSUE THREAD

**Issue by Thinkseal** [AmyMialeeMods/visiblebarriers#68]
If say you just installed the mod and you have not clicked the key bind to enable visible barriers. Barriers will not be visible at all instead of like vanilla Minecraft where they will show a barrier particle when you were holding a barrier block.

**Comment by AmyMialee** [comment]
its an option in the config

**Comment by Thinkseal** [comment]
what config?
<img width="854" alt="Screenshot 2024-09-08 at 6 57 26 PM" src="https://github.com/user-attachments/assets/e91265be-7e11-4d78-a518-8e72cc37b9e3">

**Comment by Thinkseal** [comment]
I did not know that command existed due to the fact that it's not on the modrinth page or mod description sorry
